// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module ntt_intt_pwm_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic
) (
  input clk_i,
  input rst_ni,

  // Below Register interface can be changed
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output ntt_intt_pwm_reg_pkg::ntt_intt_pwm_reg2hw_t reg2hw, // Write
  input  ntt_intt_pwm_reg_pkg::ntt_intt_pwm_hw2reg_t hw2reg, // Read

  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import ntt_intt_pwm_reg_pkg::* ;

  localparam int AW = 4;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;

  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;

  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err ;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] din_wd;
  logic din_we;
  logic [31:0] dout_qs;
  logic dout_re;
  logic ctrl_load_a_f_wd;
  logic ctrl_load_a_f_we;
  logic ctrl_load_a_i_wd;
  logic ctrl_load_a_i_we;
  logic ctrl_load_b_f_wd;
  logic ctrl_load_b_f_we;
  logic ctrl_load_b_i_wd;
  logic ctrl_load_b_i_we;
  logic ctrl_read_a_wd;
  logic ctrl_read_a_we;
  logic ctrl_read_b_wd;
  logic ctrl_read_b_we;
  logic ctrl_start_ab_wd;
  logic ctrl_start_ab_we;
  logic ctrl_start_ntt_wd;
  logic ctrl_start_ntt_we;
  logic ctrl_start_pwm_wd;
  logic ctrl_start_pwm_we;
  logic ctrl_start_intt_wd;
  logic ctrl_start_intt_we;
  logic ctrl_clear_wd;
  logic ctrl_clear_we;
  logic status_qs;
  logic status_re;

  // Register instances
  // R[din]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("WO"),
    .RESVAL  (32'h0)
  ) u_din (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (din_we),
    .wd     (din_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.din.q ),

    .qs     ()
  );


  // R[dout]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_dout (
    .re     (dout_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.dout.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (dout_qs)
  );


  // R[ctrl]: V(False)

  //   F[load_a_f]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_load_a_f (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_load_a_f_we),
    .wd     (ctrl_load_a_f_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.load_a_f.q ),

    .qs     ()
  );


  //   F[load_a_i]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_load_a_i (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_load_a_i_we),
    .wd     (ctrl_load_a_i_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.load_a_i.q ),

    .qs     ()
  );


  //   F[load_b_f]: 2:2
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_load_b_f (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_load_b_f_we),
    .wd     (ctrl_load_b_f_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.load_b_f.q ),

    .qs     ()
  );


  //   F[load_b_i]: 3:3
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_load_b_i (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_load_b_i_we),
    .wd     (ctrl_load_b_i_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.load_b_i.q ),

    .qs     ()
  );


  //   F[read_a]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_read_a (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_read_a_we),
    .wd     (ctrl_read_a_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.read_a.q ),

    .qs     ()
  );


  //   F[read_b]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_read_b (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_read_b_we),
    .wd     (ctrl_read_b_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.read_b.q ),

    .qs     ()
  );


  //   F[start_ab]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_start_ab (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_start_ab_we),
    .wd     (ctrl_start_ab_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.start_ab.q ),

    .qs     ()
  );


  //   F[start_ntt]: 7:7
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_start_ntt (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_start_ntt_we),
    .wd     (ctrl_start_ntt_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.start_ntt.q ),

    .qs     ()
  );


  //   F[start_pwm]: 8:8
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_start_pwm (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_start_pwm_we),
    .wd     (ctrl_start_pwm_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.start_pwm.q ),

    .qs     ()
  );


  //   F[start_intt]: 9:9
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_start_intt (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_start_intt_we),
    .wd     (ctrl_start_intt_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.start_intt.q ),

    .qs     ()
  );


  //   F[clear]: 10:10
  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_ctrl_clear (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_clear_we),
    .wd     (ctrl_clear_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.clear.q ),

    .qs     ()
  );


  // R[status]: V(True)

  prim_subreg_ext #(
    .DW    (1)
  ) u_status (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (status_qs)
  );




  logic [3:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == NTT_INTT_PWM_DIN_OFFSET);
    addr_hit[1] = (reg_addr == NTT_INTT_PWM_DOUT_OFFSET);
    addr_hit[2] = (reg_addr == NTT_INTT_PWM_CTRL_OFFSET);
    addr_hit[3] = (reg_addr == NTT_INTT_PWM_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = 1'b0;
    if (addr_hit[0] && reg_we && (NTT_INTT_PWM_PERMIT[0] != (NTT_INTT_PWM_PERMIT[0] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[1] && reg_we && (NTT_INTT_PWM_PERMIT[1] != (NTT_INTT_PWM_PERMIT[1] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[2] && reg_we && (NTT_INTT_PWM_PERMIT[2] != (NTT_INTT_PWM_PERMIT[2] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[3] && reg_we && (NTT_INTT_PWM_PERMIT[3] != (NTT_INTT_PWM_PERMIT[3] & reg_be))) wr_err = 1'b1 ;
  end

  assign din_we = addr_hit[0] & reg_we & ~wr_err;
  assign din_wd = reg_wdata[31:0];

  assign dout_re = addr_hit[1] && reg_re;

  assign ctrl_load_a_f_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_load_a_f_wd = reg_wdata[0];

  assign ctrl_load_a_i_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_load_a_i_wd = reg_wdata[1];

  assign ctrl_load_b_f_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_load_b_f_wd = reg_wdata[2];

  assign ctrl_load_b_i_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_load_b_i_wd = reg_wdata[3];

  assign ctrl_read_a_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_read_a_wd = reg_wdata[4];

  assign ctrl_read_b_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_read_b_wd = reg_wdata[5];

  assign ctrl_start_ab_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_start_ab_wd = reg_wdata[6];

  assign ctrl_start_ntt_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_start_ntt_wd = reg_wdata[7];

  assign ctrl_start_pwm_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_start_pwm_wd = reg_wdata[8];

  assign ctrl_start_intt_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_start_intt_wd = reg_wdata[9];

  assign ctrl_clear_we = addr_hit[2] & reg_we & ~wr_err;
  assign ctrl_clear_wd = reg_wdata[10];

  assign status_re = addr_hit[3] && reg_re;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = dout_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = '0;
        reg_rdata_next[1] = '0;
        reg_rdata_next[2] = '0;
        reg_rdata_next[3] = '0;
        reg_rdata_next[4] = '0;
        reg_rdata_next[5] = '0;
        reg_rdata_next[6] = '0;
        reg_rdata_next[7] = '0;
        reg_rdata_next[8] = '0;
        reg_rdata_next[9] = '0;
        reg_rdata_next[10] = '0;
      end

      addr_hit[3]: begin
        reg_rdata_next[0] = status_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Assertions for Register Interface

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))


endmodule
